### ISSUE TITLE
Integració Sprint 3

### ISSUE THREAD

**Issue by gpascualg** [eloipuertas/ES2015A#120]
Bones a tots!

Com sabreu el dia 5 comencen els examens i l'entrega d'aquest 3r sprint és pel dia 4.

Per evitar haver d'integrar els dies anteriors als examens i que tots puguem estudiar, l'Eloi va proposar que féssim una demo per aquest dimecres que consistís amb els bugfixes com a mínim.

Per tant, i amb l'esperança de tenir una integració més amena, dèiem d'establir una data límit pel Dilluns 26 a les 23h, tothom hauria de tenir a les respectives branques de grup el codi perfectament funcional.

Com sabreu estic integrant Travis CI al GitHub, que bàsicament dirà quins commits compilen i executen correctament. De la mateixa forma que establim una data límit per facilitar la integració, se suposa que tot codi ha de compilar i executar abans de la integració.

Proposo, i comenteu que en penseu, que si una branca (de grup) no compila/executa s'agafi l'últim commit que compili d'abans de la data límit.

Això té una part molt bona, i és que la integració serà molt més directa i fàcil, i una de "dolenta", que si algú puja codi que no funciona, aquest codi no quedarà integrat. Partint de que tothom té la responsabilitat de revisar el seu codi abans de pujar-l'ho, no ho vec molt greu.

Parlo de codi, però també s'aplica a models (prefabs) que hauran de tenir tots els components correctament posats per tal d'executar bé el joc.

Recapitulant, es proposa:
1. Codi funcional a les branques de grup (devel_a, devel_b, devel_c i devel_d), que seran les branques a integrar ABANS del deadline
2. Deadline pel DILLUNS 26 a les 23h

Qualsevol opinió (a favor o en contra) serà benvinguda, són propostes, però en qualsevol cas cal arribar a un concens quan abans millor. Duplicó a GitHub perquè quedi constància, i si ho parlem i comentem per allí encara millor!

**Comment by gpascualg** [comment]
A falta de corregir un bug resultant de la pròpia integració, està tot integrat a `devel`.
Possiblement es creï un tag un cop estigui el bugfix.

Totes les branques de grup estan també actualitzades a `devel`. Inclouen el codi per `Travis`, a falta d'activar-l'ho. Per ara i fins que ho avisi per aquí no refieu dels resultats que dongui, he de comprobar que realment estigui funcionant bé :+1: 

Podreu visualitzar l'estat de `Travis` desde (per ara reporta que no està actiu):
https://travis-ci.org/eloipuertas/ES2015A

**Comment by eloipuertas** [comment]
Travis Ja està activat! 👍
El dia 27/10/2015 2:38 a. m., "Guillem Pascual Guinovart" <
notifications@github.com> va escriure:

**Comment by gpascualg** [comment]
Perfecte! Avisaré quan estigui llest (en principi avui mateix), les proves que havia fet eren amb un projecte més petit i alguna cosa canvia amb aquest, però res que no tingui solució :smile:

**Comment by gpascualg** [comment]
L'sprint 3 ja ha acabat, tanco aquesta issue i ja se'n farà un altre quan estiguem més aprop de la data límit (ie. una setmana abans).
