### ISSUE TITLE
War machine elf

### ISSUE THREAD

**Issue by jdalmauc88** [eloipuertas/ES2015A#202]
DESCRIPTION:

Elf war machine (lanzavirotes)

OUTCOME EXPECTED / ACCEPTANCE CRITERIA:

Completely Integrable character with light in the MAP.

Estimated time effort: 4h

**Comment by gpascualg** [comment]
No se si arribo a temps de comentar això, o si ja està parlat amb @eloipuertas i ho vol així, però normalment les màquines de guerra en el warhammer clàssic (maquetisme) es classifiquen en:
- Catapulta
- Canyons
- Llençavirots (Lanzavitores)
- Canyó llençaflames
- (Skaven) "Lanzallamas de disformidad Skaven"
- D'altres concretes/especials

Mentre que una àguila aniria potser en la categòria de `criatures voladores` (com també ho fan els dracs) o `monstres`.

No dic que hagi de ser així, a la fi i el cap hauríem de tendir a simplificar certs aspectes, però per tenir-ho en compte.

Em surten alguns dubtes també:
- Podrà volar?
- L'àguila en si ataca? Si ho fa, ho fa des de l'aire o des de terra?

Com a nota, en l'apartat de "muntar" sobre vehicles, també existeixen els `carros`.

---

Sigui el que sigui, s'ha de parlar molt bé i aclarir-ho, perquè ara mateix no hi ha cap mena de lògica que controli de forma especial aquesta unitat, i no es comportaria de forma diferent que potser un light army normal.

**Comment by eloipuertas** [comment]
Si tens rao,  per elfs serien els lanzavirotes els monstres mes endavant
potser
El dia 05/11/2015 9:36 p. m., "Guillem Pascual Guinovart" <
notifications@github.com> va escriure:

**Comment by jdalmauc88** [comment]
El problema de les catapultes,Llençavirots,cayons... es que algú haurà de fer el moviment de les roques,o boles, o els objectes que es van lançant, y jo podria fer el moviment de la catapulta per exemple, però la forma que es mourà en el mapa el projectil l'hauria de fer doncs al´gu dels programadors, en el cas dels arquers o els guerrers a distancia, es va decidir no fer el projectil que es mou, però en aquest cas, quedaria molt raro que no sortís de la "war machine" ningun objecte, per això també me decidit amb l'àguila.
Si creieu que es millor fer alguna altre cosa diguem-ho i ho canvio, però teniu k tenir en compte això dels projectils.

**Comment by eloipuertas** [comment]
Hola,
El dissenyador només ha de fer el model del projectil, i l'efecte 
especial de la sang o caure a terra en xocar, el so i l'efecte de vent.  
el grup C s'encarregarà de moure'l d'A a B i fer aparéixer els efectes 
especials.

**Comment by gpascualg** [comment]
Jo vec més problemàtica l'àguila, que ha de volar per sobre del mapa i per tant ignorar obstacles, gestionar el seu atac, com ha de ser atacada... que no pas el projectil, que a la fi i el cap serà moure un objecte d'una posició A una B, com comenta l'eloi.

Suposo que dissenyant per separat la màquina en sí en un model i en un altre el projectil serà més que suficient.

**Comment by jdalmauc88** [comment]
ok, doncs ja esta canviat

**Comment by jdalmauc88** [comment]
http://www.games-workshop.com/resources/catalog/product/600x620/99810212001_ReaperBoltThrowerNEW01.jpg
(img del Llençavirots)
Al fer el llençavirots, m'he adonat que el model del warhammer no te rodes, llavors per poder moure'l pel mapa es necessari, o que algú l'empeny (llavors per cada pj s'hauria de ferla animació per moure'l) i posar rodes o com alternativa, que un dels "obrers" o soldats el pugui muntar i desmuntar on ell vol, però nomes el pot muntar dins d'un radi, per l'estil el llençavirots desapareix i el te equipat un pj, i aquest es mou, i el col·loca en un altre lloc, i torna aparèixer la arma on ell l'ha col·locat.

**Comment by gpascualg** [comment]
És realment un tema complicat, ja que en maquetisme no totes les maquines de guerra tenen moviment. Ara bé, en el nostre cas, no vec sentit a que una màquina de guerra no es pugui moure.

M'agrada la idea de que es pugui desmuntar i tornar a muntar en un altre lloc (com dius, en un radi X de la unitat que l'agafi), seria potser lo més semblant a l'original. De fet però no limitaria als obrers o als soldats, simplement que qui l'agafi tingui una penalització de moviment (ie. que es mogui més lent).

Afegir rodes o que es mogui sol no ho vec :/ 

A veure quines idees més surten! :)
