### ISSUE TITLE
"Create the game logo"

### ISSUE THREAD

**Issue by mgdiez** [eloipuertas/ES2015A#3]
**DESCRIPTION:**
At the moment, we don't have the design of the main logo of the game.

**OUTCOME EXPECTED / ACCEPTANCE CRITERIA:**

· Logo is designed.

**STORY POINTS:** 4

**Comment by mgdiez** [comment]
Here is a preview of the main logo using the title "March Wars":

<img width="300" alt="logoesw" src="https://cloud.githubusercontent.com/assets/9119829/10194192/b13c0e2e-6787-11e5-993d-00eed9b9b169.png">

Any suggestion or opinion is welcome! :)

**Comment by gpascualg** [comment]
M'encanta! Molt bona feina :)

**Comment by 4nc3str4l** [comment]
Com mola!!! 

És molt net. Queda bé el joc que has aconseguit entre la M i la W.

**Comment by eloipuertas** [comment]
Molt gran, el concepte el trobo genial! Potser els contorns externs del
logo massa fins, els faria mes gruixuts x tenir mes contrast i sembli mes
contundent, mes heavy
El dia 30/09/2015 17:39, "4nc3str4l" notifications@github.com va escriure:

**Comment by mgdiez** [comment]
Dit i fet! A la demo estarà amb els contorns externs mes gruixuts :D
