### ISSUE TITLE
Guia ràpida. Redimensió de textures.

### ISSUE THREAD

**Issue by jackure** [eloipuertas/ES2015A#300]
### DESCRIPTION:

Cal definir unes mides per les textures dels buildings i personatges. 
Cal crear plantilles de cada format.
Cal fer una guia ràpida de redimensionament de textures.
### OUTCOME EXPECTED / ACCEPTANCE CRITERIA:

S'espera crear uns [standard de textures](https://github.com/eloipuertas/ES2015A/wiki/Design-decisions), així com una [guia intuïtiva](https://github.com/eloipuertas/ES2015A/wiki/Adaptar-textures-als-standards-amb-plantilles-%28Photoshop%29) de redimensió de les imatges.

**Comment by gpascualg** [comment]
Merci Jacint! :+1:
