### ISSUE TITLE
Improve appearance of the selected elements

### ISSUE THREAD

**Issue by hermetico** [eloipuertas/ES2015A#334]
# Description

So far, the when selecting elements, a white square was shown. After talking with different members of the groups we've decided to try a different approach.
# Acceptance criteria
- [x] Different appearance for different races
- [x] Different appearance between heroes and other units of the same race
- [x] Improve life bar

**Comment by hermetico** [comment]
# Changes

Now, we are using a projector to project a mask over the terrain. 
- Heroes have a different mask, in order to find out fastly where is the heroe when there are many units in a particular place.
- Elves are green and Men are red.
- Life bar is a bit smaller, it would need somewhat improvement, though. There is still a small bug while showing the life bar, as we can see  beneath one of the heavy army selected in the picture. There is a tiny green line and it should not be there

![selection_030](https://cloud.githubusercontent.com/assets/3168437/11366727/6cc9debc-92af-11e5-8127-13992ec90dfc.jpg)

# What now

Integration hasn't been done yet

**Comment by eloipuertas** [comment]
Awesome!  It Fucking rocks!
El dia 24/11/2015 1:33 p. m., "hermetico" notifications@github.com va
escriure:

**Comment by gpascualg** [comment]
:+1: Impresionant!

**Comment by hermetico** [comment]
#373 Done, closing this one too
