### ISSUE TITLE
Estat de l'integració

### ISSUE THREAD

**Issue by 4nc3str4l** [eloipuertas/ES2015A#34]
Bones

En @gpascualg  i jo hem integrat el que hem fet a devel d fins ara:
- Hem posat la càmera amb el seu controlador.
- Hem afegit a un cub 1x2x1 l'script de Unit (juntament amb un RigidBody).
- Hem posat el mapa que ha fet en @jackure .
- Hem enfocat la càmera cap al punt on hi ha tot (tot i que es pot moure lliurement).

Els canvis s'han fet en aquest commit:

68d73aa5203f7e2b58abcbf3c54000ef2bfd55a7

Merci a tots i molts ànims

PD: En aquesta issue podriem anar informant de l'estat de l'integració

**Comment by gpascualg** [comment]
Abans parlant amb @4nc3str4l hem cregut bona idea que, de cara a la integració d'aquest diumenge, cada grup designi mínim 1 persona per fer la integració (dic mínim perque si voleu ser 2 o 3 o més, millor, així en cas de problemes és més probable tenir algú que sàpiga d'aquella classe en concret). La intensió és coordinar-ho amb hangouts/skype.

Recordo que la integració dels grups C i D la vam programar per diumenge a les 22h, per si surten problemes poder reaccionar.
Teòricament la integració de models és dilluns a les 22h, pero sí ho veieu prou avançat com per fer-ho diumenge, guai ;) I sinó cap problema!

Dit això, aneu comentant cada grup qui s'apunta (i de quin grup sou, així no cal buscar-ho).

---

Per part del grup D, de moment som @4nc3str4l i @gpascualg @jackure

**Comment by gpascualg** [comment]
Integració a `master` feta i tot funcionant. Afegida release `Sprint1`.

**Comment by gpascualg** [comment]
Hola a tots!

Per tal d'intentar no apurar a última hora i dormir una mica, hauríem de tenir-ho tot integrat a devel abans de les 23.30h (pels fans del Barça, abans de les 20:45h).

Això inclou a programadors i dissenyadors. Tot hauria d'estar llest per fer les últimes proves i ajustar els codis que tinguin dependències entre ells.

Els dissenyadors, tingueu en compte que si teniu conflictes en l'escena relatius als models, podeu borrar-los. Es farà tot per codi.

Si us plau, integreu i proveu sobre ES2015, no les altres escenes. D'altre forma acabem amb el codi dividit i res funcionant en cap escena.

Recordar que tot prefab ha de tenir un Animator (si cal poseu-l'ho buit, pero poseu-l'ho).

En principi això es tot,

Sort i ànims!

**Comment by gpascualg** [comment]
Amb permís, i ja que la vaig reobrir jo, tanco la issue!
