### ISSUE TITLE
AI Architect Algorithm

### ISSUE THREAD

**Issue by 4nc3str4l** [eloipuertas/ES2015A#340]
### Description

AI needs to be smarter in it's style of bulding the base. 

This is necessary because Base architectures need to be planned taking in account some kind of factors like:
- Game Difficulty.
- Terrain Position.
- Civilizations.
- Etc...

Also it would be cool that AI base architectures couldn't be predicted by the user because there are planned with some kind of randomness.
### Acceptance Criteria
- [x] Make Different Architectures for diferents levels of difficulty.
- [x] Create some way to allow base to adapt to different terrain positions.
- [x] Create Different base architectures taking in account the Civilization of the AI.
- [x] Give to this system some kind of randomness  (Optional).

**Estimated time effort: 6h**

**Comment by 4nc3str4l** [comment]
Progressos:

He creat un sistema que sap mapejar algo aixi:

![legend](https://cloud.githubusercontent.com/assets/6674976/11445563/8939938c-952d-11e5-8ab6-6786cfbc937a.PNG)

Al joc:

![process](https://cloud.githubusercontent.com/assets/6674976/11445567/925cd5dc-952d-11e5-9fbc-7fb4ba29d828.PNG)

Encara em falta afinar molt l'algorisme però crec que la part dificil (matemàtica) i la de parsejar els pixels de la imatge ja està feta.

Aquesta nit espero tenir un sistema que si jo pinto un mapa amb el paint seguint la llegenda de colors correcte l'arquitecte de la IA sapiga com ha de contruir la base tenint en compte llocs contruibles o no (ara mateix construiria sobre del llac xD).

**Comment by 4nc3str4l** [comment]
Vale, he resolt molts dels problemes que he tingut i la IA ja és capaç de construir seguint el patró dels planols que li passi l'arquitecte:

![process2](https://cloud.githubusercontent.com/assets/6674976/11446459/7f1bc640-9537-11e5-8bbe-26ce074497d3.PNG)

Com es pot veure es lo bastant flexible com perque un mateix mapa d'adapti a diferents relleus:

![process3](https://cloud.githubusercontent.com/assets/6674976/11446522/4609da76-9538-11e5-96c5-ed2fda8b9716.PNG)

**Comment by gpascualg** [comment]
Molt guai, així serà fàcil tenir diferents configuracions :wink:

**Comment by 4nc3str4l** [comment]
Finalment la IA sap construir bé les cantonades, no pensanva que trigaría tanta estona en algo tan intrascendent com això:

![progess elfs](https://cloud.githubusercontent.com/assets/6674976/11452180/68c22dbe-95df-11e5-959c-40692a5826af.PNG)

Però bueno els resultats son correctes:

![progress 2](https://cloud.githubusercontent.com/assets/6674976/11452288/d5315ac6-95e2-11e5-8a1b-ef3f1a4def72.PNG)
