### ISSUE TITLE
Unity peta quan es vol jugar un altre cop

### ISSUE THREAD

**Issue by c30zD** [eloipuertas/ES2015A#375]
Hi ha un problema que fa que Unity deixi de funcionar i tanqui si es vol jugar un altre cop. Això passa tant si es guanya o perd i cliquem el botó de tornar a jugar, com si sortim del joc (amb el "pause menu") i tornem a jugar.

He provat i això està passant després de la integració. A la branca del grup C, abans de la integració (commit b477dfa), no passa. Però en els commits següents a la integració sí que passa.

He provat el joc amb Unity 5.2.3 i a un altre company li va passar el mateix amb Unity 5.2.1

**Comment by c30zD** [comment]
Algú més pot confirmar si passa a la seva branca després de fer el merge (o abans)?

**Comment by gpascualg** [comment]
Aquesta tarda ho comprobo. Recast pot tenir algo a veure, però si abans no passava se'm faria raro que ara sí.

En qualsevol cas, s'hauria de fer una neteja del Recast "antic" quan es fa una nova partida, treballaré en això.

**Comment by mgdiez** [comment]
Algú te problemes amb Unity? Em funcionava bé fins que avui, al obrir Unity
em surt un error 'UnwrapCL.exe has stopped working' :S Quina versió de
Unity esteu utilitzant? S'ha canviat algo que produeixi aquest error en
versions diferents? (Tinc la mateixa versió desde el principi de semestre)

2015-11-27 15:25 GMT+01:00 Guillem Pascual Guinovart <
notifications@github.com>:

**Comment by mgdiez** [comment]
Update: Estava a 5.2.1, he actualitzat a 5.2.3 i sembla que ja va bé :) Per
si algú es troba a la mateixa situació!

Salut

2015-11-27 18:08 GMT+01:00 Marc González Díez marcgdiez@gmail.com:

**Comment by gpascualg** [comment]
@mgdiez A quina branca et pasaba això? Potser algú ha actualitzat a 5.2.3 i ha pujat algo que és incompatible amb anteriors. Millor si ja està arreglat, però així ho provem.

Ara provo l'ho de "tornar a jugar".

**Comment by gpascualg** [comment]
Mea culpa:

```
Unity Editor [version: Unity 5.2.2f1_3757309da7e7]

Recast.dll caused an Access Violation (0xc0000005)
  in module Recast.dll at 0033:63b85b60.

Error occurred at 2015-11-27_222400.
P:\Program Files\Unity\Editor\Unity.exe, run by Guillem.
27% memory in use.
16285 MB physical memory [11737 MB free].
18717 MB paging file [13197 MB free].
134217728 MB user address space [134214934 MB free].
Write to location 00000000 caused an access violation.
```

M'ho miro amb prioritat, perdoneu les molèsties!
(M'assigno a la issue, **1h**)

**Comment by gpascualg** [comment]
Està arreglat, tot i que ni la mitat de bé del que m'agradaria. De fet, salten Asserts quan es surt... M'ho miraré en detall més endavant, avui no tinc temps i preferia algo "rudimentari" però que funcioni.

Si algú ho pot provar i mirar que vagi tot bé em faria un gran favor!

**Comment by c30zD** [comment]
He provat amb Unity 5.2.3f1 i continua passant. Provaré ara amb 5.2.1f1

**Comment by gpascualg** [comment]
@c30zD Ho he fet a `devel`, has fet pull? De totes maneres estic treballant ara en una versió millor

**Comment by gpascualg** [comment]
@c30zD Prova des d'aquest nou commit que acabo de fer: 84bcaa88dfd71a7632d885f8e94b9cc4b9bbf8d4

He solucionat tots els errors previs i, teòricament, hauria de ser bastant més segur :/

**Comment by c30zD** [comment]
D'acord. Ho hauré de provar una mica més tard, perquè des que vaig fer el comentari fins ara, Unity encara està compilant tots els assets.

També, hi ha un qüestió que segurament hauria d'haver comentat abans, però no hi vaig pensar. Quan vaig provar amb Unity 5.2.3, abans era a una altra branca, vaig fer `git clean` i després vaig fer el checkout a devel (i després pull). Un cop fet tot això, ho vaig provar, però no sé si va quedar alguna cosa de la branca d'abans. En tot cas, després de la primera prova, sí que vaig fer un clean des del directori principal (l'altre clean va ser al directori "March Death")

**Comment by gpascualg** [comment]
Ook! Realment es recomenable fer un `git clean -fxd` quan es canvia de versió de Unity, amb la pega de que haurà de reimportar-ho tot... 

Per ara totes les proves que he fet han anat bé i no he detectat cap crash. He fet el commit sobre `devel` perquè he considerat que era un error prou gran com per fer-ho sobre una branca comuna. Sorry no haver-ho dit abans..

**Comment by c30zD** [comment]
Bé, doncs, el darrer commit (84bcaa8) sí que funciona. Vaig haver de provar-lo primer amb Unity 5.2.3, perquè després del clean, la versió 5.2.1 va petar, amb el problema de l'UnwrapCL. Tot i així, després d'haver provat amb la versió 5.2.3, vaig obrir el projecte amb la versió 5.2.1 i va funcionar.

**Comment by gpascualg** [comment]
@c30zD Peerfecte! Qualsevol cosa crea una altre issue, tanco aquesta ja que ja està solucionat
