### ISSUE TITLE
"Create the basic design of the HUD where features, information, etc. will be shown."

### ISSUE THREAD

**Issue by mgdiez** [eloipuertas/ES2015A#4]
**DESCRIPTION:**
Create the basic design of the HUD for this sprint, so that developers can use as a skeleton.

**OUTCOME EXPECTED / ACCEPTANCE CRITERIA:**

· A basic HUD ( to be improved on future sprints ready to be used by programmers )

**STORY POINTS: 16**

**Comment by mgdiez** [comment]
I changed the name from "Create the design where the features of units and buildings will be shown." to "Create the basic design of the HUD where features, information, etc. will be shown." and from now until the issue is closed, its assigned to Carlos Navas, due to try to finish faster this part of design assigned to team C (US with High Priority).

**Comment by cnavas88** [comment]
DESCRIPTION:
Create the basic design of the HUD for this sprint, so that developers can use as a skeleton.

OUTCOME EXPECTED / ACCEPTANCE CRITERIA:

· A basic HUD ( to be improved on future sprints ready to be used by programmers )

STORY POINTS: 16
