### ISSUE TITLE
Integration war machine and arrows

### ISSUE THREAD

**Issue by jdalmauc88** [eloipuertas/ES2015A#411]
DESCRIPTION:

Integration war machine, and arrows for animations of archers and buildings 

Estimated time effort: 1h

**Comment by jdalmauc88** [comment]
@aviaplana donde quieres que te deje el prefab de las flechas?

**Comment by aviaplana** [comment]
Yo lo dejaria en la carpeta de utils ( ES2015A/March Death/Assets/Resources/Prefabs/Utils/ )

**Comment by aviaplana** [comment]
No había visto que estan en la carpeta Projectiles, no he dicho nada! los cojo de allí
