### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jdalmauc88** [eloipuertas/ES2015A#412]
DESCRIPTION:

Testing for search bugs

Estimated time effort: 9h

**Comment by gpascualg** [comment]
Please, els bugs que vagis trobant documentals per aquí o algun lloc accessible per a tots, per que els puguem anar agafant/assignant i arreglar.

A més de l'error en sí mateix, aniria de fàbula el procés complet i detallat de com reproduirlo (com fer que saltin). Si pots incluir captures o videos millor que millor.

Els warnings també estaria bé tenir-los en compte i saber d'on surten, que normalment tot i no ser greus tenen un cost bastant important de performance.

Et paso alguns dels que ja tenim, i et comento alguns que tot i estar presents no sabem com reproduir i s'haurien d'intentar provocar i trobar-ne la causa:

![image](https://cloud.githubusercontent.com/assets/1239061/11576856/0993b49a-9a1a-11e5-8758-356f512f7536.png)
![image](https://cloud.githubusercontent.com/assets/1239061/11576863/1cacd660-9a1a-11e5-993a-bbdd3b8d7ec7.png)
- _AI randomly gets stuck, probably due to an exception being thrown somewhere, must be checked_: No se sap perquè passa encara
- _AI Buildings do not account as an occupied tile, player might build on top of it_: Cal comprobar si encara passa
- _Building can not, randomly, be selected. Mouse does not even change so problem may come from layer/raycast not being correctly thrown._: No se sap perquè ni com reproduir-ho

---

I després tenim les següents que ja estan localitzades i hi ha gent treballant-hi:

![image](https://cloud.githubusercontent.com/assets/1239061/11576919/6cf3d718-9a1a-11e5-8217-a47cd6f657ee.png)

---

I les següents tasques que no són ben bé bugs sinó millores a fer:

![image](https://cloud.githubusercontent.com/assets/1239061/11576941/97fa7070-9a1a-11e5-8395-998c1ff7fdab.png)

---

Ja diràs que vas trobant!

**Comment by jdalmauc88** [comment]
![bug](https://cloud.githubusercontent.com/assets/9373016/11666831/b20d1198-9dee-11e5-8eb7-951540ca170e.jpg)

Al ir al edificio, el héroe elfo se bugeo, no podía salir de donde estoy en la foto, y tampoco podían atacarme los humanos

**Comment by jdalmauc88** [comment]
No hay ninguna descripción, de que edificio voy a crear al pasar el raton por encima solo pone button 1, button2...

**Comment by gpascualg** [comment]
> Al ir al edificio, el héroe elfo se bugeo, no podía salir de donde estoy en la foto, y tampoco podían atacarme los humanos

Please dóna més detalls, hi ha alguna forma de reproduir-ho? Hi ha anat sol fins dins o "l'han empés"? Si és així, es possible que tingui algun constraint desmarcat? Sinó, com ha acabat dintre? Ha sortit l'edifici just quan ell passava per allí?

Entenc que el controlaves tu, no?

Merci!

**Comment by jdalmauc88** [comment]
Vale, el bug se genera en el momento que creas un edificio encima de la unidad, en este caso el heroe, el heroe estaba en la zona verde que hay con la silueta del edificio, entonces si lo creas el heroe se bugea dentro (supongo k con otras unidades pasa lo mismo)

![sin titulo](https://cloud.githubusercontent.com/assets/9373016/11667953/f95e8170-9df4-11e5-94a2-2d7f104338e9.jpg)

**Comment by jdalmauc88** [comment]
Al intentar crear una Elf war machine, tenia creado y seleccionado un edificio donde se crean los elf light y elf heavy, y al seleccionar el edificio de las war machines parece ser que se bugeo.

![sin titulo](https://cloud.githubusercontent.com/assets/9373016/11667405/ce08a616-9df1-11e5-9025-c7ba0d0e3a22.jpg)

Si os fijáis me salen los botones de otro edificio, cuando hice el cambio de selección de edificio, los dos se estaban construyendo.

**Comment by gpascualg** [comment]
@jdalmauc88 Just abans l'ha trobat en @srferran aquest mateix error. Està reportar per trello (hauríem de parlar aquest dimecres d'intentar reportar tots els error al mateix lloc per evitar duplicats).

Sospito que es pel nou sistema de botons, que no destrueix sinó que reaprofita. @Yue93 i @daniestrella1 es posible que no s'estiguin amagant els botons de l'edifici previ?

**Comment by Yue93** [comment]
Sí, y lo es.En la nueva forma de creación lo que hago es crear los botones nada más arrancar el juego y ocultarlos.Luego cuando seleccionamos un edificio se cambia la imagen, el método de action del botón.

**Comment by jdalmauc88** [comment]
@jackure Actualmente faltan texturas del mapa (la del agua se ve rosa) y hay alguna parte mas rosa en el mapa

**Comment by jdalmauc88** [comment]
Al crear civiles elfos (machos) no se ven @ccortessanchez 

![sin titulo](https://cloud.githubusercontent.com/assets/9373016/11763736/2b235252-a116-11e5-86af-ddea98f59067.jpg)

**Comment by srferran** [comment]
Podrias explicar en que circunstancias se produce este error?. Que no se vean cuando se producen es normal mientras no se alcanza el máximo numero de unidades, pues se situan dentro del edificio como workers. 
Que se vean barra de vida y demás fuera del edificio ( o dentro) no es normal en absoluto.

**Comment by ghost** [comment]
Buenas, os cuelgo un pequeño listado de bugs que he encontrado por ahora.

Bugs encontrados en devel, jugando en 1920x1080 y graficos fantastic fullscreen (como elfo):

-soldado pesado elfo no tiene animacion de movimiento.
-sawmill elfico parece estar girado. De este bug ya se ocupa Carlos del grupo de edificios.
-cuando le dices a una unidad que vaya a un marcador, estando este marcador muy cerca de otra unidad, la unidad que debe moverse no acaba quieta. Parece como que esta limitada por una barrera invisible que le impide acercarse mas a la otra unidad. El problema es que empieza a dar vueltas sobre si misma y a hacer cosas raras, supongo que porque el pathfinding sigue intentando encontrar un camino o algo del estilo.
-los botones parece que no desaparecen cuando seleccionas un edificio. Por ejemplo si selecciono el stronghold y luego selecciono el edificio especial, me sustituye los primeros botones pero puedo seguir creando murallas y demas aun teniendo seleccionado el edificio especial, no el stronghold.
-los edificios de recursos parece que no se pueden seleccionar. No se si es bug o por diseño. Quizas es el mismo bug mencionado antes que de manera random el juego no permite seleccionar un edificio.
-permite crear edificios como barracks encima de un soldado pesado. Puede que pase lo mismo con otras combinaciones de edificios y unidades.
-jugando en modo normal y pasados 20 minutos siguen sin aparecer humanos a atacar mis elfos. No se si es lo que debería pasar o no pero lo comento.
-el boton options del menu parece que no hace nada.

Seguire comentando por aquí lo demas que encuentre.

**Comment by Yue93** [comment]
Hola,chicos! Quería comentar si la gente puede probar el devel.De momento hay bastante errores de referencia nulo en esta rama.
![null](https://cloud.githubusercontent.com/assets/6915911/11768685/a6cec756-a1d4-11e5-9570-fa6d33f812b4.JPG)
![null2](https://cloud.githubusercontent.com/assets/6915911/11768689/b644a868-a1d4-11e5-905d-0a0f4cc1b0b1.JPG)
![null3](https://cloud.githubusercontent.com/assets/6915911/11768700/d24373a0-a1d4-11e5-91ba-6a44c02700b3.JPG)

**Comment by gpascualg** [comment]
@Yue93 Es raro, parece como si petara algo importante al principio de todo. La 1a imagen es del 1r error que sale?

En que commit estas?

**Comment by Yue93** [comment]
@gpascualg En devel, al hacer pull con lo último.Ahora estoy en el último

**Comment by gpascualg** [comment]
@Yue93 Esto es en la escena del menú? De ser así... bueno... deberíamos arreglarlo pero podría ser peor...

**Comment by Yue93** [comment]
@gpascualg Sí, estos errores sale nada más mostrar la escena del menú.
![null4](https://cloud.githubusercontent.com/assets/6915911/11768888/cc6aa9ca-a1da-11e5-9dd2-575624d4cef2.JPG)

**Comment by pmolinafe8** [comment]
Al construir la archery elfica, en cualquier parte del mapa, me la coloca al lado del Stronghold humano,  y si intento construir mas aparece al lado de la que me ha aparecido en fase de construcción pero luego se junta con la otra.
Y en el caso que elija a los humanos, de golpe me aparece una archery elfica en la misma posición, haya lo que haya colocado en esas coordenadas. 
También da problemas si creo tropas en ese edificio.

 Uno de cada grupo:
@gpascualg @jackure @hermetico 

Poneros en contacto conmigo si no me he explicado bien.

**Comment by reactor7171** [comment]
Al crear humanos desde la mina humana, los botones de crear civil y la cruz se quedan en el HUD aunque dejes de seleccionarla, sobreponiendose sobre los botones que estarian en ese lugar en los demas edificios. Si despues vas a crear humanos en la farm humana, al estar los botones de la mina por encima se crean desde la mina por ejemplo.

**Comment by ghost** [comment]
He probado el build actual de Devel y me he topado con lo siguiente:
-Al cargar el juego, en el menu principal aparecen los strongholds a unos dos o tres metros de altura y caen al suelo.
-Jugando como humano, battle y easy te mete en la partida pero no hay stronghold y no puedes hacer nada.

**Comment by ghost** [comment]
He visto que pasa lo mismo para el modo historia. Adicionalmente, si le das al boton de menu te salta directamente al panel de opciones.

**Comment by ghost** [comment]
No ocurre si juegas como elfo. Solo como humano.

**Comment by gpascualg** [comment]
Està "controlat". Si jugues des de l'editor veuràs a la consola una excepció.
Bàsicament, l'stronghold humà s'intenta construir sobre un arbre.
Recentment s'ha fet que no puguis construir sobre arbres, i per tant, no es
fa.
Com no es fa, salta un NullReference en Mision.

Està @c30zD fent-ho crec.

**Comment by ghost** [comment]
Ok, perfect.

**Comment by c30zD** [comment]
Allò de l'stronghold humà ja està solucionat a f3dbcbf784cd306fc85086dbb07896632eb95599 (pujat a devel)

**Comment by c30zD** [comment]
@daniestrella1 Pensaba escribirlo en la #399, pero ya lo hago aquí: si creas una unidad y deseleccionas el edificio, al volver a seleccionarlo, la cola de creación no se muestra.

**Comment by jdalmauc88** [comment]
el caballero humano es invisible y el light humano le ha desaparecido la textura del arma @fpadillasanchez

**Comment by jdalmauc88** [comment]
a veces hay unidades que me atacan, y no puedo verlas (como si estuvieran fuera de rango de vision) eso es normal? al menos si me atacan debería poder ver a esos enemigos no?

**Comment by jdalmauc88** [comment]
El bug que dije el otro dia que se bugeaba los pj dentro de los edificios @gpascualg se debería solucionar no permitiendo construir si hay un pj en ese sitio (o al menos es la más rapida)

**Comment by jdalmauc88** [comment]
@srferran perdón no vi tu mensaje, siempre se produce el bug, cuando sacas a los aldeanos del edificio que sea, los elfos macho son invisibles, mientras k las hembras si que se ven

**Comment by jdalmauc88** [comment]
Las war machine, parece que no se generan nunca, al menos las veces que he intentado crearlas ya no se crean.

**Comment by jdalmauc88** [comment]
@jackure algunas texturas de vegetación se ven completamente negras y otras se ven de color verde nose si es normal

**Comment by jackure** [comment]
@jdalmauc88 es cosa del fow. Suposo que en @MSoler ho te en compte.

**Comment by jackure** [comment]
@jdalmauc88 l'aigua l'hauríes de poder veure correctament. Fes un git clean.

**Comment by MSoler** [comment]
Confirmo que lo de la vegetacion negra es el shader de la FOW.
En teoria esta bien que la vegetacion sea negra siempre que no se acerque alguna unidad/edificio del jugador.
