### ISSUE TITLE
Watchtowers improvement

### ISSUE THREAD

**Issue by hermetico** [eloipuertas/ES2015A#432]
# Description

Watchtowers are quite good with the last enhancements but we should try to go a step beyond that. The idea is to allow watchtowers to center the focus onto enemies, to have a improved movement and a smarter behaviour
# Acceptance criteria
- [x] Movement with a non fixed radius
- [x] Do not freeze when an enemy dies
- [x] Optimized light halo

**Comment by gpascualg** [comment]
@hermetico Ten en cuenta que lo de que ilumine antes de estar construido no por la lógica/código. El animator tiene los tiempos de cambio entre estados fijos y no se pueden cambiar por código.
Teoricamente se tiene que arreglar en este sprint.

**Comment by hermetico** [comment]
Perfecto @gpascualg, lo miramos el miercoes con los diseñadores!
