### ISSUE TITLE
Make resources go up or down depending on the number of units

### ISSUE THREAD

**Issue by rperezde11** [eloipuertas/ES2015A#438]
Description
Right now both statistics and resources work only by building independently of how many units are inside producing. This issue has the intention of  fixing this problem. Also a serious refactoring is intended.

Acceptance Criteria
Statistics and the resources values vary correctly depending how many units are inside the resource buildings.

Story Points: 4

**Comment by srferran** [comment]
Not sure about this.
Right now collection rate is NOT independent from number of workers at resource building. If workers number is increased  collected resources are increesed too. So, where is the problem?

**Comment by rperezde11** [comment]
It is independent when it comes to the resources shown at the top.
