### ISSUE TITLE
Create the construcction grid API

### ISSUE THREAD

**Issue by 4nc3str4l** [eloipuertas/ES2015A#44]
**Description:**

Create a CostructionGrid API that can help the logic team  to perform construction tasks.

**Acceptance Criteria:**
-  Discretize a given vector to know which coordinates on de grid corresponts to the given coordinates of the map.
- Know if a given discretized coordinate is valid for construction by calculating if the surface is flat.
- Make the grid flexible enought to be resized by parameters.

**Estimated Time Effort:**

8 story points

**Comment by 4nc3str4l** [comment]
He començat a crear la API de la matriu de construcció la idea es ajudar tant a la IA com als de logica a saber si es pot construir en una posició.

El mètodes que he fet publics intentaré que no canviin de nom aixi podeu començar a contar amb ells encara que no estiguin implementats.

**Comment by 4nc3str4l** [comment]
Ja tenim una matriu de construcció a devel_d

A aquesta classe li podeu demanar les següents coses:

**1 )public Vector3 discretizeMapCoords(Vector3 position)**

Li doneu unes coordenades de món i ella et torna el centre de la  cel·la que has tocat. 

**Aquest mètode s'ha d'usar per passar les coordenades als metodes 3, 4, 5 sinó els resultats seràn catastrofics.**

**2 ) public void setNewGridDimensions(Vector2 newDimensions)**

Aquest mètode serveix per setejar les dimensions de la matriu de construcció.

**3) public void reservePosition(Vector3 buildingDiscretizedPosition)**

Aquest mètode serveix per reservar una posició (compte, abans de reservar una posició teniu que usar el **mètode 5**, ja que sinó pot ser que directament no te la reservi perque ja va ser ocupada per un altre objecte o que el terreny no sigui lo bastant plà com per construir)

**4) public void liberatePosition(Vector3 discretizedPosition)**

Aquest mètode serveix per lliberar una posició aixi torna ha estar disponible per construir-hi en ella.
Una possible utilització sería usarlo en el moment que un edifici sigui destruit.

**5 )public bool isNewPositionAbleForConstrucction(Vector3 discretizedPosition)**

Aquest métode càlcula si la zona on vols construir és lo bastant plana per posar-hi un edifici i a part mira que la posició no estigui ja reservada.

**Comment by c30zD** [comment]
Recomano juntar els mètodes `isNewPositionAbleForConstruction` (5) i `reservePosition` (3), ja que són gairebé idèntics. Si t'hi fixes, en totes dues crees un Vector2 i comproves si existeix a les posicions reservades. Podries fer-ho tot en el mateix mètode `reservePosition`, ja que no cal fer la comprovació dues vegades (primer per comprovar si s'hi pot construir i després quan reserves la posició) i en comptes de ser "void", faries que retorni un booleà si s'ha pogut reservar la posició i si el terreny és pla.
