### ISSUE TITLE
Close gates for enemies, open for allies

### ISSUE THREAD

**Issue by hermetico** [eloipuertas/ES2015A#451]
# Description

Now that we have gates for the walls, we should give them the possibility to be closed for the enemies. That is the point in having walls. So the idea is to attach a script to the wall prefab to make them a smart gates and provide a complete wall system for our fortress
# Acceptance criteria
- [x] Walls should let allies come in
- [x] Walls should shut the way to enemies
- [x] Clean code and feasible to be attached easily

**Comment by hermetico** [comment]
Yeah @gpascualg,  they work 3e894a894bb41e3a9bcf829f764150dd249805c8 
Nice job #466 !!

**Comment by hermetico** [comment]
## Bonus
- [x] When gates are open to let the allies go through, enemies can take advantage of this and go through them as well

**Comment by gpascualg** [comment]
@hermetico ueeeh! nice to know it's working :+1:
