### ISSUE TITLE
Animate Male Human Farmer

### ISSUE THREAD

**Issue by fpadillasanchez** [eloipuertas/ES2015A#50]
Basic movement.

**Comment by fpadillasanchez** [comment]
12h time estimated.

**Comment by raulvega26** [comment]
DESCRIPTION:

Basic movement

OUTCOME EXPECTED / ACCEPTANCE CRITERIA:
Male human with animations integrated

Estimated time effort: 6h

**Comment by fpadillasanchez** [comment]
DESCRIPTION:

Basic movement

OUTCOME EXPECTED / ACCEPTANCE CRITERIA:
Fix animation of male human.
Check animation while game running

Estimated time effort: 1h
