### ISSUE TITLE
Resolve problems of Elf Male Animation

### ISSUE THREAD

**Issue by ccortessanchez** [eloipuertas/ES2015A#51]
DESCRIPTION:

Create basic movement animations 

OUTCOME EXPECTED / ACCEPTANCE CRITERIA:
Elf with animations integrated 

Estimated time effort: 12h

**Comment by raulvega26** [comment]
DESCRIPTION:

Create basic movement animations

OUTCOME EXPECTED / ACCEPTANCE CRITERIA:
Elf with animations integrated

Estimated time effort: 6h
