### ISSUE TITLE
Stronghold destruction doesn't trigger the function "OnBuildingDestroyed" of MissionStatus class

### ISSUE THREAD

**Issue by c30zD** [eloipuertas/ES2015A#517]
No he provat si passa a l'escena principal, però a les campanyes sí ho he observat. Pel que he vist, ni tan sols es detecta l'stronghold amb el FOW:

```
Subscriber<FOWEntity.Actions, FOWEntity>.get.registerForAll(FOWEntity.Actions.DISCOVERED, OnEntityFound, selector);
Subscriber<FOWEntity.Actions, FOWEntity>.get.registerForAll(FOWEntity.Actions.HIDDEN, OnEntityLost, selector);
```

Al AIController, línies 84 i 85, i la funció del AIController OnEntityFound:

```
void OnEntityFound(System.Object obj)
{
    IGameEntity g = ((GameObject)obj).GetComponent<IGameEntity>();
    if (g.info.isUnit)
    {
        if (!EnemyUnits.Contains((Unit)g))
        {
            g.registerFatalWounds(OnEnemyDied);
            EnemyUnits.Add((Unit)g);
        }
    }
    else if (g.info.isBuilding)
    {
        if (!EnemyBuildings.Contains(g))
        {
            g.registerFatalWounds(OnEnemyDied);
            EnemyBuildings.Add(g);
        }
    }
}
```

Quan ha de fer la comprovació de si és un edifici, mai es crida en el cas de ser un stronghold, per la qual cosa tampoc cridarà OnEnemyDied, que és on es fa la crida a la funció del títol.

**Comment by c30zD** [comment]
I tampoc es crida en el cas que l'humà destrueixi l'stronghold de l'enemic.

**Comment by c30zD** [comment]
He trobat el problema: els prefabs dels strongholds tenen un script de tipus FOWEntity, el qual s'ha d'afegir dinàmicament amb les priopietats adequades. Aquest script tenia propietats que feien impossible d'utilitzar-lo bé, i clar, sempre que es feia alguna cosa amb FOWEntity, el `GetComponent` retornava el primer.

**Comment by c30zD** [comment]
Ara, hi ha un altre problema: sembla que el MissionController mai inicialitza el diccionari correcte.

**Comment by c30zD** [comment]
Ja està arreglat. Era un problema a l'hora d'inicialitzar els paràmetres de la campanya. b1104bc3162cfb5b567d9b010e46f7e94481b1ae

**Comment by c30zD** [comment]
No sé si hi ha alguna semblança amb #187, però de vegades no surt la pantalla de finalització del joc. A les campanyes he trobat que de vegades surt un error amb l'StrategyAgent:

```
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[UnityEngine.Vector3].get_Item  (Int32 index) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
Assets.Scripts.AI.Agents.StrategyAgent.controlUnits (.Squad squad) (at Assets/Scripts/AI/Agents/StrategyAgent.cs:62)
Assets.Scripts.AI.MicroManager.Micro () (at Assets/Scripts/AI/MicroManager.cs:84)
Assets.Scripts.AI.AIController.Update () (at Assets/Scripts/AI/AIController.cs:104)
```

No sé si el fet que la IA es trobi en un estat "d'error" pugui ser la causa, ja que la IA ha de notificar que ha eliminat l'stronghold. Ara, bé, he pensat que no és la causa, sinó que és cosa de Unity, però com que hi ha un problema amb la IA, us ho comunico @4nc3str4l @MSoler @gpascualg

**Comment by MSoler** [comment]
El Error aquest esta arreglat a partir de 3457313cf74b9a3ab9968767c61476e0d3d7a844, pero la pantalla de finalitzacio segueix sense sortir, aixi que segurament sigui això que dius de unity.

**Comment by c30zD** [comment]
Tanco la issue perquè ja està solucionat el tema de l'stronghold. Quant a la pantalla de finalització del joc, he obert una altra issue, ja que és una qüestió molt diferent. #522
