### ISSUE TITLE
Playing again does not reset the story mission

### ISSUE THREAD

**Issue by c30zD** [eloipuertas/ES2015A#520]
MissionController class is reset, but MissionStatus class is not.

**Comment by gpascualg** [comment]
T'ho comentava per l'altre issue, però mira't aquest commit:
f97fe98e8b5688f18f89f3323d93b930b1e39f98

Vaig fer refactoring d'algunes coses, tema reiniciar / alliberar referències.

**Comment by gpascualg** [comment]
Pot ser que de forma no intencionada s'arreglés ahir en un dels comits per arreglar la seqüència de missions de la campanya?
