### ISSUE TITLE
Base class for Units (interface)

### ISSUE THREAD

**Issue by gpascualg** [eloipuertas/ES2015A#6]
### Description

Base interface for Units, basic API funcionality and parent class for advanced/specified units
### Acceptance Criteria
- Advanced units should be able to extend/implement from this class.
- Pull information from #5 
- Other classes should be able to query basic information of units
  - Current state (health...)
  - Unit type
  - Unit specs
- Instantiable from editor, prefabs and dynamically from #5 

**Estimated time effort: 3 hours**

**Comment by gpascualg** [comment]
Per tal de que la gent que depén de la classe Unit pugui treballar, la idea es tenir llest per dema (tarda) això:

(No pretenc fer un diagrama de tot, solament dels atributs/propietats/metodes que crec poden ser utils/cridats des d'altres llocs. D'igual forma, la idea es no modificar-ho massa a partir d'aquí, però podria patir algun canvi).
![unitdiagram](https://cloud.githubusercontent.com/assets/1239061/10114919/38075c92-63fa-11e5-8c05-b5ea6f35f4e6.png)

He optat per seguir els atributs classics del joc warhammer, ho podem parlar el següent dimecres, però us en faig un breu resum.
Es pot obtenir la informació base d'una unitat amb `objUnitat.info.attributes`.  O en cas de ser un GameObject, amb `gameObject.getComponent<Unit>().info.attributes`.
Alternativament es podria fer la crida a `Info`(no recomentat) amb: `Info.get.unit(race, type).attributes`
- weaponAbility: Habilitat d'armes, serveix per calcular la probabilitat d'encertar un cop (i parar-l'ho)
- projectileAbility: Igual que l'anterior, pero a distància
- strength: Si encerta el cop, la força d'aquest
- resistance: Si rep un cop, la possibilitat de parar-lo sense ferida
- wounds: Màxim de ferides que pot rebre una unitat
- attack_rate: Atacs per segon
- movement_rate: Moviment per segon

Existeixen taules de valors ja definits, juntament amb taules per calcular impactes i dany (https://github.com/eloipuertas/ES2015A/blob/6c8854dbae6b6386c2bbb095f4695f1585b22c09/March%20Death/Assets/Scripts/Storage/HitTables.cs)

Funciona amb certa aleatorietat, segons la tirada d'un dau de 6 cares.
Les formules estan implementades en 6c8854dbae6b6386c2bbb095f4695f1585b22c09

L'herència d'Actor serveix per subscriure's a events, com ara la mort de la unitat. Es fa servir internament per deixar d'atacar un cop s'ha matat l'objectiu, però també es podria fer servir des de fora per altres coses. També es pot extendre a d'altres events.

**Comment by gpascualg** [comment]
Si algú ho necessita ja està a `devel_d`. No treballeu amb el codi de `devel_d-unit_api` perquè molt probablement encara canviarà aquest.

**Comment by gpascualg** [comment]
Després de parlar amb el grup c i relacionat amb el tema edificis, modificarem una mica l'esquema d'adalt per intentar crear una classe base que agrupi unitats i edificis, per fer més fàcil l'obtenció de dades per la UI.

No canviarà molta cosa, la idea és unificar unitats i edificis, i accedir a través de `gameObject->getComponent<GameEntity>()`, enlloc d'haver d'actuar diferent en cas de `Unit` o `Building`.
L'atribut `info` es mantindrà practicament igual, excepte per la inclusió de les `Ability`, que serviran pel menú que també desenvolupa el grup c.

Aprofito per llençar 3 preguntes a l'aire, que aquest dimecres hauríem de debatir:
1. Les unitats poden recuperar vida? Si ho fan, com? Ajuntant unitats ferides, recuperació per segon o amb habilitats? (jo, de fer-ho, opto per l'ho últim)
2. Les accions de click a les unitats/edificis, implementats a `GameEntity` (la nova classe base) o en un script diferent? (per evitar 2 grups modificant 1 sol arxiu)
3. El moviment, s'implementa directament en Unit i cadascú (grup c, mov. usuari; grup d, mov. IA) el crida? O com ho voleu fer?

**Comment by hermetico** [comment]
Hola,
He estado trabajando en la seleccion de elementos del mapa [#15]. He creado un par de clases, pero supongo que lo imporante es la clase que unificarian las unidades y los edificios ( igual se deberian incluir las fuentes de recursos de los mapas, por ejemplo que al seleccionar una mina te indique el % de recursos de los que dispone). Pero supongo que en este caso se deberia tratar de forma diferente.

Yo he implementado los clicks en una clase llamada UserInput, mas que nada por que ahora que hay seleccion unica es facil, pero supongo que se complicara a la hora de seleccionar multiples unidades.
El codigo no esta adjuntado todavia por que tenia pendiente de hacer una pregunta de este estilo, tras hablarlo con los de mi grupo, y asi si tengo que cambiar nombres y mover funciones sera mas rapido

**Comment by gpascualg** [comment]
Seria interesante que los recursos tambien fuera parecido, cierto, pero como comentas le veo poco punto en común con los edificios/unidades. Quizás se podría generalizar incluso más la clase padre, pero si lo llevamos muy al extremo dejaría de ser útil para lo demás (probablemente habría que hacer un cast para los casos que no sean recursos).

Soluciones viables, que vea:
1. Generalizar mucho la clase padre, pero la verdad no me gusta mucho
2. Crear otra clase padre, de forma que quede Padre1 -> Recurso i GameEntity, y para lo demás que herede de GameEntity. Aún así habría que distinguir casos, y tal por tal, no se si es mejor que los recursos tengan una clase a parte.
3. Clase a parte para los recursos

Personalmente, no veo suficiente relación entre recursos y unidades/edificios (en cuanto a que describe los objectos) para juntarlo, pero en cualquier caso, queda por debatir. Cito a @srferran, que está con el tema recursos.

Perfecto por lo del click, esa era una de las cuestiones que tenía (2) y la verdad yo también opto por seprarlo. Supongo que ya lo habéis hablado, pero cito a @daniestrella1 y @Yue93, que estaban en el ajo también.

**Comment by hermetico** [comment]
Vale, entonces el diagrama este que adjunto seria algo _parecido_ a la solucion 3?
![diagram](https://cloud.githubusercontent.com/assets/3168437/10162703/57a5533c-66ad-11e5-9074-5bf3fbbbfb5f.jpg)

**Comment by gpascualg** [comment]
Practicamente sí. Te muestro uno que hice ayer para enseñar al grupo (es más o menos lo que hay hecho de momento, le sobran y le faltan algunas cosas).
![entity](https://cloud.githubusercontent.com/assets/1239061/10163736/3342ae06-66b5-11e5-9971-258ba98a2d1e.png)

Veo que hay un `ChangeSelection` i un `OnClick` en IGameEntity. Queréis que los ponga? (Y que lo implemente Unit/Building).
De buildings no hay nada puesto, pero asume que será algo parecido.

**Comment by gpascualg** [comment]
Perdón que no vi lo de la solución 3. Realmente, sí pero no jaja 
Es decir, de momento he hecho esto, pero es relativamente sencillo hacer que IGameEntity herede de algo más y implementar la 1/2. Aunque, si por mi fuera, a lo sumo la 2 o a 3.

**Comment by gpascualg** [comment]
Bueno, en principi això es més o menys definitiu per aquest sprint (falta la info de Building que la afegirem més tard):
(He separat per colors les parts/APIs diferents que poden interesar a differents grups)
![entity_diagram](https://cloud.githubusercontent.com/assets/1239061/10202915/7c4413fc-67b3-11e5-8e67-69b39fc466e0.png)

Ara documentaré a la wiki com fer servir cadascuna de les parts, i en global com s'integra i funciona. Juntament amb el tema prefabs d'unitats i com crear-los.

Respecte crear prefabs d'unitats, la meva intenció és simplificar el mètode de cara a aquest cap de setmana. Ara per ara demana Raça i Tipus, però tenint en compte que un prefab ja ho té predefinit, no caldria.

**Comment by gpascualg** [comment]
Fent la docu he vist que hi havia alguna petita inconsistència i que faltava un mètode, `getAction`. Actualitzo el diagrama per si algú el necessita.

També aprofito per linkar l'entrada de la docu (work in progress) de la wiki:
https://github.com/eloipuertas/ES2015A/wiki/Entity-API

![entity_diagram](https://cloud.githubusercontent.com/assets/1239061/10204718/b107933e-67bd-11e5-855b-9777d1abc406.png)

**Comment by gpascualg** [comment]
La interfície en sí mateixa està ja definida i, a menys que per algun requisit calgui, no hauria de canviar.

Si que hi ha canvis plantejats de cara a l'sprint 2, però aquests no modificarien els mètodes públics que exposa actualment la API. Per tant, considero apropiat tancar aquesta issue i, en tot cas, obrir-ne de noves pel següent sprint, fent referència exactament al que calgui modificar.

Compleix tots els requisits, l'herència en concret no s'implementa ja que finalment s'utiltizen els JSON.
