### ISSUE TITLE
Create buildings

### ISSUE THREAD

**Issue by hermetico** [eloipuertas/ES2015A#73]
# Description

Create an locate buildings in the map.
# Acceptance criteria
- Create buildings
- Control the position where the buildings are created
- Show some feedback while positioning the building

Estimated effort: 6h

**Comment by hermetico** [comment]
## Descripcion ultimos cambios

Los edificios se crean utilizando un boton temporal debajo del menu de opciones. 
De momento solo se controla si la altura es adecuada, partiendo de la altura en la que estan ahora el resto de buildings.
Aparece un recuadro verde si la ubicacion es correcta y rojo si es incorrecta. Este recuadro se hace mediante el Debug.Lines, esta pendiente de mejora con shaders, texturas, o podriamos considerar que los propios objetos tuviesen ya alguna apariencia configurada que tan solo se tuviese que activar o desactivar (Esto haria mucho mas sencilla la implementacion de cambios visuales en los objetos)
Se han añadido funciones de control en la clase Player y en la clase UserInput.
La clase Player ahora tiene un enumerador de estado, podria plantearse la posibilidad de mover este enumerador a una clase GameController.
El building se deja con el boton izquierdo del mouse y con el derecho se cancela la operación

35c6db5bfe9b76bf43b396e946dde3bcd000675a

**Comment by hermetico** [comment]
Encontrado un pequeño problema a la hora de interactuar con los botones del HUD. Al momento de despues de ejecutar las acciones al evento onClick de los botones, se estan lanzando eventos tip onMouseButtonUp. Estos eventos se deben de controlar, por ejemplo comprobando si la zona clicada es zona de hud, o con alguna solucion mejor.

**Comment by hermetico** [comment]
Los edificios se caen al colocarlos sobre el mapa

**Comment by hermetico** [comment]
Actualizada la funcionalidad de buildings manager. Se controla la posicion de los edificios. Se ha ajustado la tolerancia del constructionGrid y se incorporan nuevos cursores para dar un feedback de si se puede construir o no un edificio. Mas adelante se mostrara tmb con un shader sobre el propio building. Asi queda ahora mismo:
![nobuild](https://cloud.githubusercontent.com/assets/3168437/10776313/9b2a435a-7d10-11e5-8393-7e418915c15e.jpg)

Falta restar los recursos necesarios de un edificio a la hora de ubicarlo

**Comment by gpascualg** [comment]
Perfecto! Me gusta como va quedando ;)

**Comment by hermetico** [comment]
Gracias a los ghost building se ha simplificado bastante la logica en la clase Buildings manager.
Ahora mismo tan solo se muestra un ghost building, comun a todos. Mas adelante se incorporarán el resto. Debido a la simplicidad de los cambios que quedan se considera cerrada esta issue, eso y que las condiciones de aceptación ya se cumplen.
