### ISSUE TITLE
Add working textures and animation for Human Stronghold.

### ISSUE THREAD

**Issue by ghost** [eloipuertas/ES2015A#80]
**DESCRIPTION**:

Textures for the Human Stronghold were added in the previous sprint however I couldn't get them to work. This needs to be fixed.

Additionally the building should have some sort of idle animation (waving flags, etc).

**OUTCOME EXPECTED / ACCEPTANCE CRITERIA**:

Fully textured and animated Human Stronghold.

Estimated time effort: 10h

**Comment by ghost** [comment]
Only one side of the flag is visible. Due to removal of a shader that was producing errors inside unity after merging branches.

**Comment by lays1989** [comment]
**DESCRIPTION:**

change shader for Flag

**OUTCOME EXPECTED / ACCEPTANCE CRITERIA:**

shader flag is changed

**Estimated time effort:** 1h

**Comment by lays1989** [comment]
This just opened at #139
