### ISSUE TITLE
Units consume food, civils can both generate or consume gold

### ISSUE THREAD

**Issue by gpascualg** [eloipuertas/ES2015A#84]
### Description

All units consume food (per second/tick), which should be taken from the player/IA resources. In a similar way, civils units besides consuming food can produce gold if working in a Resource Building or consume it otherwise.
### Acceptance Criteria
- All units consume food
- Civils produce gold if they are in a resource generating building, or consume them otherwise.

**Estimated time effort: 2h**

**Comment by gpascualg** [comment]
Comparteixo una taula amb possibles valors de producció/consum de gold/food.
- Taula 1: Valors per tipus d'unitat (en producció/segon i consum/segon).
- Taula 2: Per 10 o 100 unitats d'un tipus, quants civils calen per equilibrar l'or (deixar-l'ho a 0)
- Taula 3: Si tenim un exercit com el de la taula, amb diferent nombre d'unitats de diferents tipus, calcular:
  1. Consum d'or i menjar
  2. Mínim nombre de civils per equilibrar gold
  3. Mínim nombre de civils per equilibrar food
  4. Mínimes unitats per equilibrar tant gold com food `max(2, 3)`
  5. Com les unitats mínimes per equilibrar (5) també menjen, cal incloure-les (approx. en el càlcul) => Camp `Aprox.` del full
  6. Relació `Civils/Army` per aquet exèrcit, i produccions total.

Feu un cop d'ull i opineu a veure, potser caldrà canviar números, adaptar, etc. Un cop provat en el joc també caldrà tornar-ho a verificar.

**Comment by gpascualg** [comment]
Ui, compartir la taula sense l'enllaç és un pel complicat:
https://docs.google.com/spreadsheets/d/1M8UPtgGJU1FYvSFXGjpGt0-lmf1NaswH2vbfUqWEgFY/edit?usp=sharing

**Comment by c30zD** [comment]
Jo crec que els civils no hauríen de consunir or. Si l'or és important pel
joc (quant al consum), com ara que les unitats només treballin per or,
podria passar que no existeixi una font d'ingresos (destrucció de
buildings, no haver-hi recursos, etc.) i que al final no es pugui fer res.
Ara bé, si als civils no els afecta la manca d'or, llavors tampoc té gaire
sentit que en consumeixin. A més a més, els civils són súbdits, fan el que
digui l'amo i prou. :)

Tot i haver-hi casos en què tindria sentit el consum d'or (com ara poder
anar a la taverna), trobo que és més fàcil que els civils només produeixin
or —quantes cerveses han de beure per tal de poder pagar als soldats,
tenint en compte que els civils també en consumeixen, d'or? I si cal que
tothom begui?—.

**Comment by gpascualg** [comment]
El que comentavem abans es que un civil pot estar fent dues coses:
1. Treballant en un edifici que genera recurs, i per tant generant/produint or a mes
2. Explorant o lluitant (llegeixis morint), i en aquest cas consumint or.

En qualsevol cas, no produiria i consumiria a la vegada, i si asumim que la majoria de civils estaran en recursos, normalment produiran.

Pel que havia entes jo l'or era important de cara a poder fer millores d'edificis, tot i que em sembla un molt bon punt el de que sense or l'exercit no "obeeixi".

En canvi el menjar afectava mes directament als civils, si no n'hi ha no treballen (excepte els que estiguin en granjes, està clar, d'altre banda no tindria sentit seguir jugant si et quedes sense menjar).

Tal i com ho enfocava, així com un civil o produeix or o en consumeix, si que pot estar consumint menjar i produint-ne (menjar sempre ho farà, si està en una granja, a més en produirà).

Personalment no penalitzaria la manca d'or/menjar amb la destruccio o mort de res. Tot i que des d'un punt de vista de realisme la fam hauria de matar gent, en quant a jugabilitat un error (enviar tots els civils, o gran part a la guerra i que te'ls matin) podria suposar perdre a curt/llarg plaç (segons el _rate_ al que morin).

És a dir, ho vec interesant, afegiria realisme, però hauria d'estar molt ben "delimitat" per no arruinar el joc amb massa complexitat.

A veure que més diu la gent i que n'opina el product owner =P

**Comment by eloipuertas** [comment]
Hola,

Si voleu simplificar el càlcul podem fer que en el que es produeix en la 
granja ja es té en compte el que mengen els grangers així aquest no cal 
contar-los com consumidors. Els demés si que haurien de consumir tots 
una unitat de menjar mínim (pot ser més segons convingui). En el cas del 
civil explorant, podem dir que ni genera ni consumeix or, sí però 
menjar. És més barat que un soldat, però bastant més ineficient.

  Bé com tot joc ha d'acabar-se, suposant que l'IA fos molt tonta i no 
acabés mai amb el jugador d'alguna forma, el joc s'hauria d'acabar per a 
inactivitat de l'humà, això pot ser que si hi ha fam (food < 0) degut 
que a cada unitat de temps t hi ha una pèrdua de food proporcional al 
nombre de civils i donat que les Farms tenen una producció limitada per 
una quantitat N, podem dir que arribarà en algun punt que la funcio f(t) 
(f de food) serà menor a 0; llavors podem fer que la producció i la 
recaptacio baixi a la meitat (p(t)/2, r(t)/2) , en el cas de food < 0 i 
or < 0, (r(t) és proporcional al nombre de població total - q, on q és 
un valor fixat d'or que es consumeix cada unitat de t de forma 
constant,  en cas de gana f<0, la recaptació d'or es reduïria a la mitat 
i el valor q aumentaria exponencialment a t, sent cada cop més car 
controlar la població. Llavors, eventualment r(t)< 0 i f(t)<0 serien 0 
amb el temps si l'humà no fa res. En aquest cas pot haver-hi un motí que 
faci que els civils i army ataquin al stronghold, independenment de la 
partida, que estiguis fent, si stronghold es destruït perds.

**Comment by gpascualg** [comment]
Ja es té en compte la generació i consumisió de gold i food en les `Unit`. Queda implementar la reducció/penalització, pero ja que aquesta classe feia referència a `Unit`, es farà una altre issue.
